@startuml
title FDT - Login y Seguridad

node "Módulo Login y Seguridad" {
    node "Autenticación" {
        [Ingresar Usuario]
        [Ingresar Contraseña]
        [Validar Credenciales]
    }

    node "Autorización" {
        [Asignar Roles]
        [Permisos por Módulo]
        [Control de Accesos]
    }

    node "Gestión de Sesiones" {
        [Iniciar Sesión]
        [Cerrar Sesión]
        [Recordar Usuario]
    }
}
@enduml
