@startuml
left to right direction
actor Administrador
actor Usuario

rectangle "Sistema de Seguridad" {
  Administrador --> (Crear Rol)
  Administrador --> (Asignar Permisos)
  Administrador --> (Editar Rol)
  Administrador --> (Eliminar Rol)
  Usuario --> (Iniciar Sesión)
  Usuario --> (Acceder a Funciones según Rol)
}
@enduml
