@startuml
class Producto {
  -id: int
  -nombre: string
  -stock: int
}

class Movimiento {
  -id: int
  -tipo: string
  -cantidad: int
  -fecha: Date
}

Producto "1" <-- "0..*" Movimiento
@enduml
